# Generated by Django 5.1.2 on 2024-11-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproducts',
            name='pid',
            field=models.IntegerField(default=None),
        ),
    ]
